name: Parse parts lists

on: [push]

jobs:
  generate_md:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install ruff pytest
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: generate_parts_list_md
        run: |
          cd parts_list
          python3 csv_to_md.py
      # push the changes if any
      - uses: int128/update-generated-files-action@v2
